services:
  filesync:
    image: kryksyh/filesync
    container_name: filesync-app
    environment:
      - SECRET_KEY=<SECRET_KEY>
    ports:
      - "80:80"
    depends_on:
      - peerjs
    restart: unless-stopped

  peerjs:
    image: peerjs/peerjs-server:1.1.0-rc.2
    container_name: filesync-peerjs
    command: peerjs --path /peerjs
    depends_on:
      - coturn
    restart: unless-stopped

  coturn:
    image: coturn/coturn:alpine
    container_name: filesync-coturn
    command:
      - --fingerprint
      - --use-auth-secret
      - --no-multicast-peers
      - --realm=filesync.app
      - --static-auth-secret=<SECRET_KEY>
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
    restart: unless-stopped